version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: attendance-postgres
    ports:
      - "5122:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: attendance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: attendance-backend
    ports:
      - "3403:3403"
    depends_on:
      - postgres

  employee-attendance:
    build: ./Employee-attendance
    container_name: employee-attendance-ui
    ports:
      - "8304:80"
    depends_on:
      - backend

  hr-attendance:
    build: ./HR-attendance
    container_name: hr-attendance-ui
    ports:
      - "8305:80"
    depends_on:
      - backend

volumes:
  postgres_data:

